# Generated by Django 5.1.1 on 2024-09-20 11:23

import django.db.models.deletion
import ulid
import ulid_django.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', ulid_django.models.ULIDField(default=ulid.ULID, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='UserFromTelegram',
            fields=[
                ('telegram_id', models.PositiveBigIntegerField(db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='Telegram ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Russian')], default='en', max_length=2, verbose_name='Language')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', ulid_django.models.ULIDField(default=ulid.ULID, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Task Title')),
                ('description', models.TextField(verbose_name='Task Description')),
                ('completed', models.BooleanField(default=False, verbose_name='Completed')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Due Date')),
                ('categories', models.ManyToManyField(related_name='tasks', to='ToDoBot_API.category', verbose_name='Categories')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ToDoBot_API.userfromtelegram', verbose_name='Task Author')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', ulid_django.models.ULIDField(default=ulid.ULID, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='Comment Text')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ToDoBot_API.task', verbose_name='Task')),
            ],
        ),
    ]
